default:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  resolved_paths: &ref_0 []
  cache_manifest: false
  extract_css: false
  static_assets_extensions: &ref_1
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  extensions: &ref_2
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
development:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: true
  webpack_compile_output: true
  resolved_paths: *ref_0
  cache_manifest: false
  extract_css: false
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: true
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: 'localhost:3035'
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      Access-Control-Allow-Origin: '*'
    watch_options:
      ignored: '**/node_modules/**'
test:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs-test
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  resolved_paths: *ref_0
  cache_manifest: false
  extract_css: false
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: true
production:
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  resolved_paths: *ref_0
  cache_manifest: true
  extract_css: true
  static_assets_extensions: *ref_1
  extensions: *ref_2
  compile: false
