default: 
  cache_manifest: false
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  extensions: 
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  extract_css: false
  public_output_path: packs
  public_root_path: public
  resolved_paths: []
  source_entry_path: packs
  source_path: app/javascript
  static_assets_extensions: 
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  webpack_compile_output: true
development: 
  cache_manifest: false
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: true
  compile: true
  dev_server: 
    compress: true
    disable_host_check: true
    headers: 
      Access-Control-Allow-Origin: "*"
    hmr: false
    host: localhost
    https: false
    inline: true
    overlay: true
    port: 3035
    pretty: false
    public: "localhost:3035"
    quiet: false
    use_local_ip: false
    watch_options: 
      ignored: "**/node_modules/**"
  extensions: 
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  extract_css: false
  public_output_path: packs
  public_root_path: public
  resolved_paths: []
  source_entry_path: packs
  source_path: app/javascript
  static_assets_extensions: 
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  webpack_compile_output: true
production: 
  cache_manifest: true
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  compile: false
  extensions: 
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  extract_css: true
  public_output_path: packs
  public_root_path: public
  resolved_paths: []
  source_entry_path: packs
  source_path: app/javascript
  static_assets_extensions: 
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  webpack_compile_output: true
test: 
  cache_manifest: false
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  compile: true
  extensions: 
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
  extract_css: false
  public_output_path: packs-test
  public_root_path: public
  resolved_paths: []
  source_entry_path: packs
  source_path: app/javascript
  static_assets_extensions: 
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  webpack_compile_output: true
